fix ping schedule bug
youngmonkeys/ezyfox-server-android-client pull request #12
Opened 2021-09-01 14:07 UTC by tvd12

2021-09-01 22:55 UTC, vu-luong requested changes
Em thấy file `gradle.properties` trống, mình có nên ignore nó không anh?

2021-09-02 01:25 UTC, tvd12 reviewed
@vu-luong anh fix rồi nhé, review lại giúp anh với nhé

2021-09-02 01:54 UTC, vu-luong commented
@tvd12 Em thấy code ok rồi, có cần em cài Android Studio và máy ảo để test không ạ?

2021-09-02 02:30 UTC, tvd12 commented
@vu-luong có em ạ, bản android này dùng chung cho cả react-native và flutter nên rất quan trọng em ạ

2021-09-03 04:09 UTC, vu-luong requested changes

2021-09-03 04:12 UTC, tvd12 commented on build.gradle
> +//apply plugin: 'io.github.gradle-nexus.publish-plugin'
không em ạ, nó dùng để anh deploy lên maven em ạ

2021-09-03 04:13 UTC, tvd12 commented on gradle.properties
> +# project.repo=https://github.com/youngmonkeys/ezyfox-server-android-client
file này thực tế là nằm trong cấu trúc dự án của gradle, mình cứ tạm thời để đó em ạ

2021-09-03 04:16 UTC, tvd12 commented
@tvd12 review lai giup anh voi nhe

2021-09-03 04:34 UTC, vu-luong approved these changes
LGTM!

2021-09-03 04:39 UTC, merged